# The following properties are required for repper (productive) deployment.
# For productive deployment, all properties must be configured or enabled.
# Only relevant properties should be listed here; otherwise, they should be deleted.
# Unless otherwise specified, empty properties are relevant and must be configured.
# Temporary disabled properties require further configuration or other dependencies.

##############################################################################
# Basic                                                                      #
##############################################################################
# Configure base url, e.g. http://domain:port, without '/'. Temporary disabled to use default.
#MCR.baseurl=
# Requires MCR.baseurl, therefore temporary disabled.
#MIR.CanonicalBaseURL=%MCR.baseurl%/
MCR.NameOfProject=pnet
MIR.projectid.default=pnet

# Add french to supported languages.
MCR.Metadata.Languages=de,en,fr

##############################################################################
# Access Control                                                             #
##############################################################################
# Enable access keys for mods objects and derivates
MCR.ACL.AccessKey.Strategy.AllowedObjectTypes=mods,derivate

##############################################################################
# Email                                                                      #
##############################################################################
MCR.Mail.Server=
# General sender mail address, e.g. mail@domain
MCR.Mail.Sender=

# Mail for events including self registration, e.g. <name> mail@domain
MCR.mir-module.EditorMail=
# Sender email for events, e.g. <name> mail@domain
MCR.mir-module.MailSender=
MCR.mir-module.sendEditorMailToCurrentAuthor=true

##############################################################################
# Editor                                                                     #
##############################################################################
# Customization of XEditor forms
MIR.EditorForms.CustomIncludes=%MIR.EditorForms.CustomIncludes%,xslStyle:editor/mir2xeditor:webapp:editor/editor-customization.xed

##############################################################################
# DOI Config                                                                 #
##############################################################################
MCR.DOI.HostingInstitution=Max Weber Stiftung

# Configuration is required, therefore service temporary disabled.
#MCR.PI.Service.Datacite=org.mycore.pi.doi.MCRDOIService
MCR.PI.Service.Datacite=org.mycore.pi.doi.MCRDOIService
MCR.PI.Service.Datacite.Username=
MCR.PI.Service.Datacite.Password=
MCR.PI.Service.Datacite.Transformer=datacite
MCR.PI.Service.Datacite.RegisterBaseURL=%MCR.baseurl%/
MCR.PI.Service.Datacite.RegisterURLContext=receive/$ID
MCR.PI.Service.Datacite.MetadataService=MODSDOI
MCR.PI.MetadataService.MODSDOI=org.mycore.mods.identifier.MCRMODSDOIMetadataService
MCR.PI.MetadataService.MODSDOI.Prefix=10.25360/01-
MCR.PI.Service.Datacite.Generator=repperDOI
MCR.PI.Generator.repperDOI=org.mycore.pi.MCRGenericPIGenerator
MCR.PI.Generator.repperDOI.GeneralPattern=10.25360/01-$ObjectDate-$Count
MCR.PI.Generator.repperDOI.DateFormat=yyyy
MCR.PI.Generator.repperDOI.CountPrecision=5
MCR.PI.Generator.repperDOI.Type=doi

##############################################################################
# OAI                                                                        #
##############################################################################
MCR.OAIDataProvider.OAI2.RepositoryName=Publikationsplattform der Max Weber Stiftung
MCR.OAIDataProvider.OAI2.RepositoryIdentifier==%MCR.baseurl%
MCR.OAIDataProvider.OAI2.AdminEmail=
MCR.OAIDataProvider.OAI2.DescriptionURI.EPrints=webapp:oai/oai-eprints.xml
MCR.OAIDataProvider.OAI2.DescriptionURI.Rights=webapp:oai/oai-rights.xml
MCR.OAIDataProvider.OAI2.RecordSampleID=pnet_mods_00001119

# Set metadata formats.
MCR.OAIDataProvider.MetadataFormat.oai_datacite.Namespace=http://schema.datacite.org/oai/oai-1.0/
MCR.OAIDataProvider.MetadataFormat.oai_datacite.Schema=http://schema.datacite.org/oai/oai-1.0/oai_datacite.xsd
MCR.OAIDataProvider.OAI2.MetadataFormats=oai_dc,mods,oai_datacite

# Define set specifications.
MCR.OAIDataProvider.OAI2.Sets=doc-type,open_access,openaire,driver,ec_fundedresources,GENRE,ddc
MCR.OAIDataProvider.OAI2.Sets.ddc.URI=xslStyle:classification2sets:classification:metadata:10:children:DDC
MCR.OAIDataProvider.OAI2.Sets.ddc.Classification=DDC

MCR.OAIDataProvider.RunListRecordsParallel=false

##############################################################################
# ePuSta                                                                     #
##############################################################################
# ePuSta endpoint is required, therefore temporarily disabled.
#MIR.ePuSta=show
MIR.ePuSta.providerURL=

##############################################################################
# Frontend                                                                   #
##############################################################################
MIR.CustomLayout.JS=repper.js

MCR.LayoutTransformerFactory.Default.Stylesheets=%MCR.LayoutTransformerFactory.Default.Stylesheets%,xsl/i18n-transformation-step.xsl,xsl/xhtml2html.xsl

# Enable solr search and WCMS templates for MyCoReWebPage.
MCR.URIResolver.xslIncludes.MyCoReWebPage=%MCR.URIResolver.xslIncludes.MyCoReWebPage%,solrSearch.xsl,wcmsTemplates.xsl

# Add download and cover box to layout.
MIR.Layout.End=repper-download-box,mir-edit,mir-citation,series-banner,series-layout,mir-access-rights,repper-cover-box,mir-epusta,mir-export,mir-admindata,mir-historydata

# Override mcr_error to show OA error page without StackTrace.
MCR.ContentTransformer.mcr_error.Stylesheet=xsl/errorPage.xsl,%MCR.LayoutTransformerFactory.Default.Stylesheets%

# Adapt table of contents output.
MIR.TableOfContents.MaxResults=10000
MIR.TableOfContents.LevelLimit=1000
MIR.TableOfContents.RolesToDisplay=cre aut edt rev

# Enable DataCite export format.
MCR.Export.Transformers=mods:MODS,datacite:DataCite,bibtex:BibTeX,endnote:Endnote,ris:RIS,isi:ISI,mods2csv:CSV

# Override citation styles.
MIR.citationStyles=din-1505-2

##############################################################################
# WCMS                                                                       #
##############################################################################
# TODO usage?
MCR.WCMS2.mycoreTagList=toc, printlatestobjects, de, en, fr

##############################################################################
# Batch Processing                                                           #
##############################################################################
MCR.BatchEditor.praeUrl.Path2Remove=mods:location/mods:url[contains(text(),"{0}")]

MCR.BatchEditor.BaseLevel.relatedhost=/mycoreobject/metadata/def.modsContainer/modsContainer/mods:mods/mods:relatedItem[@type="host"]/mods:part
MCR.BatchEditor.volume.Path2Remove=mods:detail[@type="volume"][mods:number/text()="{0}"]

MCR.BatchEditor.license.Path2Remove=mods:accessCondition[@xlink:href="http://www.mycore.org/classifications/mir_licenses#{0}"]
MCR.BatchEditor.license.Path2Add=mods:accessCondition[@type="use and reproduction"][@xlink:type="simple"][@xlink:href="http://www.mycore.org/classifications/mir_licenses#{0}"]

##############################################################################
# Sitelinks                                                                  #
##############################################################################
# Active Sitelinks servlet.
MCR.Servlet.SitelinksServlet.Disabled=false

##############################################################################
# Alias Plugin                                                               #
##############################################################################
MCR.Alias.prefix=publikationen/

##############################################################################
# Navigation Plugin                                                          #
##############################################################################
MCR.LayoutTransformerFactory.Default.Ignore=%MCR.LayoutTransformerFactory.Default.Ignore%,mycoreobject-rss
REP.RSS.Generator=perspectivia.net\: Publikationsplattform der Max Weber Stiftung, Bonn, Germany
